[2021-06-15 14:20:27,974] {scheduler_job.py:182} INFO - Started process (PID=25) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:20:27,975] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:20:27,976] {logging_mixin.py:104} INFO - [2021-06-15 14:20:27,976] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:20:28,958] {logging_mixin.py:104} INFO - [2021-06-15 14:20:28,958] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:20:28,959] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:20:28,979] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 1.009 seconds
[2021-06-15 14:20:59,177] {scheduler_job.py:182} INFO - Started process (PID=56) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:20:59,178] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:20:59,179] {logging_mixin.py:104} INFO - [2021-06-15 14:20:59,179] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:21:01,285] {logging_mixin.py:104} INFO - [2021-06-15 14:21:01,280] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:21:01,285] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:21:01,364] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 2.191 seconds
[2021-06-15 14:22:15,940] {scheduler_job.py:182} INFO - Started process (PID=75) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:22:16,027] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:22:16,157] {logging_mixin.py:104} INFO - [2021-06-15 14:22:16,146] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:23:17,607] {scheduler_job.py:182} INFO - Started process (PID=89) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:23:17,611] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:23:17,613] {logging_mixin.py:104} INFO - [2021-06-15 14:23:17,612] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:23:21,948] {logging_mixin.py:104} INFO - [2021-06-15 14:23:21,931] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:23:21,953] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:23:22,108] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 4.507 seconds
[2021-06-15 14:23:52,637] {scheduler_job.py:182} INFO - Started process (PID=111) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:23:52,644] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:23:52,645] {logging_mixin.py:104} INFO - [2021-06-15 14:23:52,645] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:24:22,962] {logging_mixin.py:104} INFO - [2021-06-15 14:24:22,845] {timeout.py:36} ERROR - Process timed out, PID: 111
[2021-06-15 14:24:23,623] {logging_mixin.py:104} INFO - [2021-06-15 14:24:23,164] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/.local/lib/python3.7/site-packages/pandas/_config/__init__.cpython-37m-x86_64-linux-gnu.so'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 5, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 29, in <module>
    from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 30, in <module>
    from .conversion import OutOfBoundsTimedelta, localize_pydatetime
  File "pandas/_libs/tslibs/conversion.pyx", line 58, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/parsing.pyx", line 1, in init pandas._libs.tslibs.parsing
  File "pandas/_libs/tslibs/offsets.pyx", line 1, in init pandas._libs.tslibs.offsets
  File "pandas/_libs/tslibs/timestamps.pyx", line 47, in init pandas._libs.tslibs.timestamps
  File "pandas/_libs/tslibs/fields.pyx", line 16, in init pandas._libs.tslibs.fields
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1383, in find_spec
  File "<frozen importlib._bootstrap_external>", line 95, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py after 30.0s, PID: 111
[2021-06-15 14:24:23,974] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:24:28,599] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 35.972 seconds
[2021-06-15 14:24:58,864] {scheduler_job.py:182} INFO - Started process (PID=133) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:24:58,865] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:24:58,867] {logging_mixin.py:104} INFO - [2021-06-15 14:24:58,867] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:25:00,824] {logging_mixin.py:104} INFO - [2021-06-15 14:25:00,822] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:25:00,825] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:25:00,861] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 2.002 seconds
[2021-06-15 14:34:54,372] {scheduler_job.py:182} INFO - Started process (PID=23) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:34:54,379] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:34:54,380] {logging_mixin.py:104} INFO - [2021-06-15 14:34:54,380] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:34:54,935] {logging_mixin.py:104} INFO - [2021-06-15 14:34:54,934] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:34:54,936] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:34:54,958] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.591 seconds
[2021-06-15 14:35:25,087] {scheduler_job.py:182} INFO - Started process (PID=52) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:35:25,092] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:35:25,095] {logging_mixin.py:104} INFO - [2021-06-15 14:35:25,094] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:35:26,078] {logging_mixin.py:104} INFO - [2021-06-15 14:35:26,075] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:35:26,079] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:35:26,152] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 1.092 seconds
[2021-06-15 14:36:00,671] {scheduler_job.py:182} INFO - Started process (PID=66) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:36:01,516] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:36:03,515] {logging_mixin.py:104} INFO - [2021-06-15 14:36:03,158] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:36:18,908] {logging_mixin.py:104} INFO - [2021-06-15 14:36:18,885] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:36:18,912] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:36:19,101] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 19.809 seconds
[2021-06-15 14:36:51,485] {scheduler_job.py:182} INFO - Started process (PID=68) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:36:51,534] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:36:51,566] {logging_mixin.py:104} INFO - [2021-06-15 14:36:51,555] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:36:58,926] {logging_mixin.py:104} INFO - [2021-06-15 14:36:58,915] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:36:58,928] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:36:59,071] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 7.805 seconds
[2021-06-15 14:39:55,003] {scheduler_job.py:182} INFO - Started process (PID=23) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:39:55,004] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:39:55,005] {logging_mixin.py:104} INFO - [2021-06-15 14:39:55,005] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:39:55,557] {logging_mixin.py:104} INFO - [2021-06-15 14:39:55,557] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:39:55,558] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:39:55,579] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.583 seconds
[2021-06-15 14:40:25,661] {scheduler_job.py:182} INFO - Started process (PID=55) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:40:25,663] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:40:25,664] {logging_mixin.py:104} INFO - [2021-06-15 14:40:25,664] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:40:26,086] {logging_mixin.py:104} INFO - [2021-06-15 14:40:26,086] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:40:26,087] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:40:26,109] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.452 seconds
[2021-06-15 14:40:56,769] {scheduler_job.py:182} INFO - Started process (PID=76) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:40:56,771] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:40:56,772] {logging_mixin.py:104} INFO - [2021-06-15 14:40:56,772] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:40:57,084] {logging_mixin.py:104} INFO - [2021-06-15 14:40:57,084] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:40:57,085] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:40:57,109] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.345 seconds
[2021-06-15 14:42:11,786] {scheduler_job.py:182} INFO - Started process (PID=23) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:42:11,788] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:42:11,788] {logging_mixin.py:104} INFO - [2021-06-15 14:42:11,788] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:42:12,465] {logging_mixin.py:104} INFO - [2021-06-15 14:42:12,464] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:42:12,465] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:42:12,489] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.707 seconds
[2021-06-15 14:42:43,355] {scheduler_job.py:182} INFO - Started process (PID=57) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:42:43,358] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:42:43,359] {logging_mixin.py:104} INFO - [2021-06-15 14:42:43,359] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:42:43,994] {logging_mixin.py:104} INFO - [2021-06-15 14:42:43,993] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:42:43,994] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:42:44,017] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.667 seconds
[2021-06-15 14:43:14,520] {scheduler_job.py:182} INFO - Started process (PID=87) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:43:14,521] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:43:14,522] {logging_mixin.py:104} INFO - [2021-06-15 14:43:14,522] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:43:14,975] {logging_mixin.py:104} INFO - [2021-06-15 14:43:14,975] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:43:14,976] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:43:14,994] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.479 seconds
[2021-06-15 14:43:45,672] {scheduler_job.py:182} INFO - Started process (PID=117) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:43:45,673] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:43:45,674] {logging_mixin.py:104} INFO - [2021-06-15 14:43:45,674] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:43:46,202] {logging_mixin.py:104} INFO - [2021-06-15 14:43:46,201] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:43:46,202] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:43:46,222] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.554 seconds
[2021-06-15 14:44:16,785] {scheduler_job.py:182} INFO - Started process (PID=137) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:44:16,786] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:44:16,786] {logging_mixin.py:104} INFO - [2021-06-15 14:44:16,786] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:44:17,344] {logging_mixin.py:104} INFO - [2021-06-15 14:44:17,344] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:44:17,345] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:44:17,364] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.584 seconds
[2021-06-15 14:44:47,928] {scheduler_job.py:182} INFO - Started process (PID=166) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:44:47,931] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:44:47,932] {logging_mixin.py:104} INFO - [2021-06-15 14:44:47,932] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:44:48,458] {logging_mixin.py:104} INFO - [2021-06-15 14:44:48,457] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:44:48,458] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:44:48,481] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.558 seconds
[2021-06-15 14:45:19,067] {scheduler_job.py:182} INFO - Started process (PID=195) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:45:19,079] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:45:19,080] {logging_mixin.py:104} INFO - [2021-06-15 14:45:19,080] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:45:19,586] {logging_mixin.py:104} INFO - [2021-06-15 14:45:19,585] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:45:19,586] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:45:19,607] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.543 seconds
[2021-06-15 14:45:50,201] {scheduler_job.py:182} INFO - Started process (PID=225) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:45:50,202] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:45:50,203] {logging_mixin.py:104} INFO - [2021-06-15 14:45:50,202] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:45:50,543] {logging_mixin.py:104} INFO - [2021-06-15 14:45:50,542] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:45:50,543] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:45:50,566] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.369 seconds
[2021-06-15 14:46:21,344] {scheduler_job.py:182} INFO - Started process (PID=255) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:46:21,346] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:46:21,347] {logging_mixin.py:104} INFO - [2021-06-15 14:46:21,347] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:46:21,852] {logging_mixin.py:104} INFO - [2021-06-15 14:46:21,851] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:46:21,852] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:46:21,873] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.533 seconds
[2021-06-15 14:46:52,531] {scheduler_job.py:182} INFO - Started process (PID=275) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:46:52,533] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:46:52,534] {logging_mixin.py:104} INFO - [2021-06-15 14:46:52,533] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:46:53,117] {logging_mixin.py:104} INFO - [2021-06-15 14:46:53,116] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:46:53,117] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:46:53,139] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.612 seconds
[2021-06-15 14:47:23,667] {scheduler_job.py:182} INFO - Started process (PID=305) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:47:23,669] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:47:23,670] {logging_mixin.py:104} INFO - [2021-06-15 14:47:23,670] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:47:24,140] {logging_mixin.py:104} INFO - [2021-06-15 14:47:24,140] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:47:24,140] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:47:24,160] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.497 seconds
[2021-06-15 14:47:54,791] {scheduler_job.py:182} INFO - Started process (PID=336) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:47:54,795] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:47:54,796] {logging_mixin.py:104} INFO - [2021-06-15 14:47:54,796] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:47:55,326] {logging_mixin.py:104} INFO - [2021-06-15 14:47:55,326] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:47:55,326] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:47:55,348] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.562 seconds
[2021-06-15 14:48:25,931] {scheduler_job.py:182} INFO - Started process (PID=366) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:48:25,933] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:48:25,936] {logging_mixin.py:104} INFO - [2021-06-15 14:48:25,935] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:48:26,391] {logging_mixin.py:104} INFO - [2021-06-15 14:48:26,391] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:48:26,392] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:48:26,409] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.483 seconds
[2021-06-15 14:48:57,047] {scheduler_job.py:182} INFO - Started process (PID=396) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:48:57,048] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:48:57,049] {logging_mixin.py:104} INFO - [2021-06-15 14:48:57,049] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:48:57,494] {logging_mixin.py:104} INFO - [2021-06-15 14:48:57,494] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:48:57,495] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:48:57,515] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.475 seconds
[2021-06-15 14:49:28,162] {scheduler_job.py:182} INFO - Started process (PID=426) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:49:28,164] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:49:28,165] {logging_mixin.py:104} INFO - [2021-06-15 14:49:28,165] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:49:28,695] {logging_mixin.py:104} INFO - [2021-06-15 14:49:28,694] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:49:28,696] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:49:28,717] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.558 seconds
[2021-06-15 14:49:59,287] {scheduler_job.py:182} INFO - Started process (PID=446) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:49:59,289] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:49:59,290] {logging_mixin.py:104} INFO - [2021-06-15 14:49:59,289] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:49:59,793] {logging_mixin.py:104} INFO - [2021-06-15 14:49:59,792] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:49:59,793] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:49:59,809] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.526 seconds
[2021-06-15 14:50:30,422] {scheduler_job.py:182} INFO - Started process (PID=476) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:50:30,424] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:50:30,425] {logging_mixin.py:104} INFO - [2021-06-15 14:50:30,424] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:50:30,825] {logging_mixin.py:104} INFO - [2021-06-15 14:50:30,824] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:50:30,825] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:50:30,852] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.435 seconds
[2021-06-15 14:51:01,516] {scheduler_job.py:182} INFO - Started process (PID=507) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:51:01,529] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:51:01,530] {logging_mixin.py:104} INFO - [2021-06-15 14:51:01,530] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:51:02,031] {logging_mixin.py:104} INFO - [2021-06-15 14:51:02,030] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:51:02,032] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:51:02,054] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.540 seconds
[2021-06-15 14:51:32,647] {scheduler_job.py:182} INFO - Started process (PID=537) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:51:32,660] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:51:32,661] {logging_mixin.py:104} INFO - [2021-06-15 14:51:32,661] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:51:33,060] {logging_mixin.py:104} INFO - [2021-06-15 14:51:33,059] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:51:33,060] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:51:33,081] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.439 seconds
[2021-06-15 14:52:03,821] {scheduler_job.py:182} INFO - Started process (PID=566) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:52:03,824] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:52:03,825] {logging_mixin.py:104} INFO - [2021-06-15 14:52:03,825] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:52:04,330] {logging_mixin.py:104} INFO - [2021-06-15 14:52:04,329] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:52:04,330] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:52:04,353] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.535 seconds
[2021-06-15 14:52:34,975] {scheduler_job.py:182} INFO - Started process (PID=585) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:52:34,977] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:52:34,978] {logging_mixin.py:104} INFO - [2021-06-15 14:52:34,978] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:52:35,674] {logging_mixin.py:104} INFO - [2021-06-15 14:52:35,673] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:52:35,674] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:52:35,716] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.746 seconds
[2021-06-15 14:53:06,115] {scheduler_job.py:182} INFO - Started process (PID=615) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:53:06,117] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:53:06,118] {logging_mixin.py:104} INFO - [2021-06-15 14:53:06,118] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:53:06,652] {logging_mixin.py:104} INFO - [2021-06-15 14:53:06,651] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:53:06,653] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:53:06,677] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.575 seconds
[2021-06-15 14:53:37,251] {scheduler_job.py:182} INFO - Started process (PID=645) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:53:37,253] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:53:37,254] {logging_mixin.py:104} INFO - [2021-06-15 14:53:37,254] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:53:37,760] {logging_mixin.py:104} INFO - [2021-06-15 14:53:37,758] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:53:37,760] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:53:37,787] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.543 seconds
[2021-06-15 14:54:08,354] {scheduler_job.py:182} INFO - Started process (PID=675) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:54:08,355] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:54:08,356] {logging_mixin.py:104} INFO - [2021-06-15 14:54:08,356] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:54:08,936] {logging_mixin.py:104} INFO - [2021-06-15 14:54:08,934] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:54:08,936] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:54:08,962] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.614 seconds
[2021-06-15 14:54:39,474] {scheduler_job.py:182} INFO - Started process (PID=705) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:54:39,476] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:54:39,477] {logging_mixin.py:104} INFO - [2021-06-15 14:54:39,477] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:54:39,922] {logging_mixin.py:104} INFO - [2021-06-15 14:54:39,921] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:54:39,922] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:54:39,944] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.473 seconds
[2021-06-15 14:55:10,610] {scheduler_job.py:182} INFO - Started process (PID=725) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:55:10,612] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:55:10,613] {logging_mixin.py:104} INFO - [2021-06-15 14:55:10,613] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:55:11,106] {logging_mixin.py:104} INFO - [2021-06-15 14:55:11,105] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:55:11,106] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:55:11,126] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.520 seconds
[2021-06-15 14:55:41,717] {scheduler_job.py:182} INFO - Started process (PID=754) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:55:41,718] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:55:41,719] {logging_mixin.py:104} INFO - [2021-06-15 14:55:41,719] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:55:42,230] {logging_mixin.py:104} INFO - [2021-06-15 14:55:42,229] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:55:42,230] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:55:42,254] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.542 seconds
[2021-06-15 14:56:12,852] {scheduler_job.py:182} INFO - Started process (PID=783) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:56:12,854] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:56:12,855] {logging_mixin.py:104} INFO - [2021-06-15 14:56:12,855] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:56:13,405] {logging_mixin.py:104} INFO - [2021-06-15 14:56:13,403] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:56:13,405] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:56:13,430] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.582 seconds
[2021-06-15 14:56:43,970] {scheduler_job.py:182} INFO - Started process (PID=812) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:56:43,974] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:56:43,975] {logging_mixin.py:104} INFO - [2021-06-15 14:56:43,975] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:56:44,654] {logging_mixin.py:104} INFO - [2021-06-15 14:56:44,653] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:56:44,655] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:56:44,680] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.715 seconds
[2021-06-15 14:57:15,137] {scheduler_job.py:182} INFO - Started process (PID=842) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:57:15,139] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:57:15,140] {logging_mixin.py:104} INFO - [2021-06-15 14:57:15,140] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:57:15,642] {logging_mixin.py:104} INFO - [2021-06-15 14:57:15,640] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:57:15,642] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:57:15,664] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.531 seconds
[2021-06-15 14:57:46,267] {scheduler_job.py:182} INFO - Started process (PID=862) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:57:46,279] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:57:46,280] {logging_mixin.py:104} INFO - [2021-06-15 14:57:46,280] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:57:46,894] {logging_mixin.py:104} INFO - [2021-06-15 14:57:46,893] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:57:46,895] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:57:46,915] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.653 seconds
[2021-06-15 14:58:17,431] {scheduler_job.py:182} INFO - Started process (PID=892) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:58:17,433] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:58:17,434] {logging_mixin.py:104} INFO - [2021-06-15 14:58:17,434] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:58:18,021] {logging_mixin.py:104} INFO - [2021-06-15 14:58:18,019] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:58:18,022] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:58:18,050] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.624 seconds
[2021-06-15 14:58:48,586] {scheduler_job.py:182} INFO - Started process (PID=921) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:58:48,588] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:58:48,589] {logging_mixin.py:104} INFO - [2021-06-15 14:58:48,589] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:58:49,282] {logging_mixin.py:104} INFO - [2021-06-15 14:58:49,280] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:58:49,283] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:58:49,351] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.770 seconds
[2021-06-15 14:59:19,736] {scheduler_job.py:182} INFO - Started process (PID=950) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:59:19,738] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:59:19,739] {logging_mixin.py:104} INFO - [2021-06-15 14:59:19,739] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:59:20,395] {logging_mixin.py:104} INFO - [2021-06-15 14:59:20,393] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:59:20,396] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:59:20,454] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.723 seconds
[2021-06-15 14:59:50,885] {scheduler_job.py:182} INFO - Started process (PID=971) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:59:50,886] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 14:59:50,887] {logging_mixin.py:104} INFO - [2021-06-15 14:59:50,887] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:59:51,529] {logging_mixin.py:104} INFO - [2021-06-15 14:59:51,526] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 14:59:51,529] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 14:59:51,574] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.692 seconds
[2021-06-15 15:00:22,061] {scheduler_job.py:182} INFO - Started process (PID=1000) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:00:22,062] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:00:22,063] {logging_mixin.py:104} INFO - [2021-06-15 15:00:22,063] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:00:22,736] {logging_mixin.py:104} INFO - [2021-06-15 15:00:22,733] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:00:22,738] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:00:22,787] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.731 seconds
[2021-06-15 15:00:53,215] {scheduler_job.py:182} INFO - Started process (PID=1029) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:00:53,216] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:00:53,216] {logging_mixin.py:104} INFO - [2021-06-15 15:00:53,216] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:00:53,959] {logging_mixin.py:104} INFO - [2021-06-15 15:00:53,940] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:00:53,962] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:00:54,101] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.889 seconds
[2021-06-15 15:01:24,327] {scheduler_job.py:182} INFO - Started process (PID=1050) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:01:24,329] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:01:24,331] {logging_mixin.py:104} INFO - [2021-06-15 15:01:24,330] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:01:26,242] {logging_mixin.py:104} INFO - [2021-06-15 15:01:26,216] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:01:26,247] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:01:26,722] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 2.400 seconds
[2021-06-15 15:01:57,500] {scheduler_job.py:182} INFO - Started process (PID=1080) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:01:57,503] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:01:57,504] {logging_mixin.py:104} INFO - [2021-06-15 15:01:57,504] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:01:58,855] {logging_mixin.py:104} INFO - [2021-06-15 15:01:58,833] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:01:58,859] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:01:59,010] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 1.518 seconds
[2021-06-15 15:02:29,646] {scheduler_job.py:182} INFO - Started process (PID=1100) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:02:29,649] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:02:29,651] {logging_mixin.py:104} INFO - [2021-06-15 15:02:29,650] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:02:30,818] {logging_mixin.py:104} INFO - [2021-06-15 15:02:30,787] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:02:30,821] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:02:31,568] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 1.926 seconds
[2021-06-15 15:03:01,770] {scheduler_job.py:182} INFO - Started process (PID=1131) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:03:01,773] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:03:01,774] {logging_mixin.py:104} INFO - [2021-06-15 15:03:01,774] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:03:02,420] {logging_mixin.py:104} INFO - [2021-06-15 15:03:02,418] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:03:02,420] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:03:02,465] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.700 seconds
[2021-06-15 15:03:32,991] {scheduler_job.py:182} INFO - Started process (PID=1160) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:03:32,995] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:03:32,997] {logging_mixin.py:104} INFO - [2021-06-15 15:03:32,996] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:03:35,151] {logging_mixin.py:104} INFO - [2021-06-15 15:03:35,147] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:03:35,152] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:03:35,209] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 2.227 seconds
[2021-06-15 15:04:06,147] {scheduler_job.py:182} INFO - Started process (PID=1180) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:04:06,149] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:04:06,150] {logging_mixin.py:104} INFO - [2021-06-15 15:04:06,150] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:04:06,776] {logging_mixin.py:104} INFO - [2021-06-15 15:04:06,774] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:04:06,777] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:04:06,809] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.668 seconds
[2021-06-15 15:04:37,274] {scheduler_job.py:182} INFO - Started process (PID=1210) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:04:37,276] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:04:37,277] {logging_mixin.py:104} INFO - [2021-06-15 15:04:37,277] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:04:37,815] {logging_mixin.py:104} INFO - [2021-06-15 15:04:37,813] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:04:37,815] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:04:37,847] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.577 seconds
[2021-06-15 15:05:08,414] {scheduler_job.py:182} INFO - Started process (PID=1240) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:05:08,415] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:05:08,416] {logging_mixin.py:104} INFO - [2021-06-15 15:05:08,416] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:05:08,985] {logging_mixin.py:104} INFO - [2021-06-15 15:05:08,983] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:05:08,985] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:05:09,027] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.616 seconds
[2021-06-15 15:05:39,579] {scheduler_job.py:182} INFO - Started process (PID=1260) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:05:39,581] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:05:39,582] {logging_mixin.py:104} INFO - [2021-06-15 15:05:39,581] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:05:40,166] {logging_mixin.py:104} INFO - [2021-06-15 15:05:40,163] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:05:40,167] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:05:40,201] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.627 seconds
[2021-06-15 15:06:10,731] {scheduler_job.py:182} INFO - Started process (PID=1290) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:06:10,734] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:06:10,735] {logging_mixin.py:104} INFO - [2021-06-15 15:06:10,735] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:06:11,351] {logging_mixin.py:104} INFO - [2021-06-15 15:06:11,348] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:06:11,351] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:06:11,390] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.665 seconds
[2021-06-15 15:06:41,867] {scheduler_job.py:182} INFO - Started process (PID=1311) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:06:41,868] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:06:41,869] {logging_mixin.py:104} INFO - [2021-06-15 15:06:41,869] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:06:42,405] {logging_mixin.py:104} INFO - [2021-06-15 15:06:42,402] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:06:42,405] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:06:42,438] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.574 seconds
[2021-06-15 15:07:13,008] {scheduler_job.py:182} INFO - Started process (PID=1340) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:07:13,009] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:07:13,010] {logging_mixin.py:104} INFO - [2021-06-15 15:07:13,010] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:07:13,650] {logging_mixin.py:104} INFO - [2021-06-15 15:07:13,648] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:07:13,651] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:07:13,688] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.686 seconds
[2021-06-15 15:07:44,152] {scheduler_job.py:182} INFO - Started process (PID=1371) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:07:44,153] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:07:44,154] {logging_mixin.py:104} INFO - [2021-06-15 15:07:44,154] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:07:44,700] {logging_mixin.py:104} INFO - [2021-06-15 15:07:44,698] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:07:44,700] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:07:44,747] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.601 seconds
[2021-06-15 15:08:15,267] {scheduler_job.py:182} INFO - Started process (PID=1392) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:08:15,270] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:08:15,272] {logging_mixin.py:104} INFO - [2021-06-15 15:08:15,272] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:08:15,901] {logging_mixin.py:104} INFO - [2021-06-15 15:08:15,899] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:08:15,901] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:08:15,947] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.685 seconds
[2021-06-15 15:08:46,385] {scheduler_job.py:182} INFO - Started process (PID=1423) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:08:46,387] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:08:46,388] {logging_mixin.py:104} INFO - [2021-06-15 15:08:46,388] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:08:46,942] {logging_mixin.py:104} INFO - [2021-06-15 15:08:46,940] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:08:46,942] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:08:46,966] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.585 seconds
[2021-06-15 15:09:17,500] {scheduler_job.py:182} INFO - Started process (PID=1452) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:09:17,502] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:09:17,503] {logging_mixin.py:104} INFO - [2021-06-15 15:09:17,503] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:09:18,056] {logging_mixin.py:104} INFO - [2021-06-15 15:09:18,054] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:09:18,056] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:09:18,086] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.591 seconds
[2021-06-15 15:09:48,620] {scheduler_job.py:182} INFO - Started process (PID=1481) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:09:48,621] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:09:48,623] {logging_mixin.py:104} INFO - [2021-06-15 15:09:48,622] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:09:49,261] {logging_mixin.py:104} INFO - [2021-06-15 15:09:49,257] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:09:49,261] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:09:49,301] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.686 seconds
[2021-06-15 15:10:19,745] {scheduler_job.py:182} INFO - Started process (PID=1501) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:10:19,747] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:10:19,748] {logging_mixin.py:104} INFO - [2021-06-15 15:10:19,747] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:10:20,329] {logging_mixin.py:104} INFO - [2021-06-15 15:10:20,327] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:10:20,329] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:10:20,358] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.617 seconds
[2021-06-15 15:10:50,923] {scheduler_job.py:182} INFO - Started process (PID=1531) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:10:50,924] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:10:50,925] {logging_mixin.py:104} INFO - [2021-06-15 15:10:50,925] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:10:51,508] {logging_mixin.py:104} INFO - [2021-06-15 15:10:51,506] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:10:51,508] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:10:51,535] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.617 seconds
[2021-06-15 15:11:22,078] {scheduler_job.py:182} INFO - Started process (PID=1562) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:11:22,081] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:11:22,082] {logging_mixin.py:104} INFO - [2021-06-15 15:11:22,081] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:11:22,692] {logging_mixin.py:104} INFO - [2021-06-15 15:11:22,687] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:11:22,693] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:11:22,728] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.655 seconds
[2021-06-15 15:11:53,233] {scheduler_job.py:182} INFO - Started process (PID=1596) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:11:53,235] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:11:53,236] {logging_mixin.py:104} INFO - [2021-06-15 15:11:53,236] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:11:53,868] {logging_mixin.py:104} INFO - [2021-06-15 15:11:53,866] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:11:53,869] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:11:53,905] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.676 seconds
[2021-06-15 15:12:24,387] {scheduler_job.py:182} INFO - Started process (PID=1616) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:12:24,389] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:12:24,389] {logging_mixin.py:104} INFO - [2021-06-15 15:12:24,389] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:12:25,034] {logging_mixin.py:104} INFO - [2021-06-15 15:12:25,032] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:12:25,035] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:12:25,062] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.680 seconds
[2021-06-15 15:12:55,620] {scheduler_job.py:182} INFO - Started process (PID=1645) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:12:55,622] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:12:55,623] {logging_mixin.py:104} INFO - [2021-06-15 15:12:55,623] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:12:56,276] {logging_mixin.py:104} INFO - [2021-06-15 15:12:56,275] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:12:56,276] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:12:56,298] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.682 seconds
[2021-06-15 15:13:26,804] {scheduler_job.py:182} INFO - Started process (PID=1674) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:13:26,806] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:13:26,806] {logging_mixin.py:104} INFO - [2021-06-15 15:13:26,806] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:13:27,307] {logging_mixin.py:104} INFO - [2021-06-15 15:13:27,306] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:13:27,308] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:13:27,329] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.529 seconds
[2021-06-15 15:13:57,968] {scheduler_job.py:182} INFO - Started process (PID=1695) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:13:57,969] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:13:57,971] {logging_mixin.py:104} INFO - [2021-06-15 15:13:57,970] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:13:58,587] {logging_mixin.py:104} INFO - [2021-06-15 15:13:58,583] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:13:58,588] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:13:58,631] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.667 seconds
[2021-06-15 15:14:29,115] {scheduler_job.py:182} INFO - Started process (PID=1725) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:14:29,117] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:14:29,118] {logging_mixin.py:104} INFO - [2021-06-15 15:14:29,118] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:14:29,720] {logging_mixin.py:104} INFO - [2021-06-15 15:14:29,718] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:14:29,721] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:14:29,748] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.637 seconds
[2021-06-15 15:14:59,842] {scheduler_job.py:182} INFO - Started process (PID=1756) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:14:59,843] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:14:59,844] {logging_mixin.py:104} INFO - [2021-06-15 15:14:59,844] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:15:00,383] {logging_mixin.py:104} INFO - [2021-06-15 15:15:00,379] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:15:00,383] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:15:00,410] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.571 seconds
[2021-06-15 15:15:30,524] {scheduler_job.py:182} INFO - Started process (PID=1787) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:15:30,529] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:15:30,530] {logging_mixin.py:104} INFO - [2021-06-15 15:15:30,530] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:15:31,214] {logging_mixin.py:104} INFO - [2021-06-15 15:15:31,212] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:15:31,214] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:15:31,257] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.737 seconds
[2021-06-15 15:16:01,351] {scheduler_job.py:182} INFO - Started process (PID=1808) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:16:01,353] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:16:01,353] {logging_mixin.py:104} INFO - [2021-06-15 15:16:01,353] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:16:01,827] {logging_mixin.py:104} INFO - [2021-06-15 15:16:01,826] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:16:01,828] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:16:01,844] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.496 seconds
[2021-06-15 15:16:31,940] {scheduler_job.py:182} INFO - Started process (PID=1837) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:16:31,941] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:16:31,942] {logging_mixin.py:104} INFO - [2021-06-15 15:16:31,942] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:16:32,499] {logging_mixin.py:104} INFO - [2021-06-15 15:16:32,497] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:16:32,499] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:16:32,528] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.592 seconds
[2021-06-15 15:17:02,622] {scheduler_job.py:182} INFO - Started process (PID=1866) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:17:02,623] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:17:02,625] {logging_mixin.py:104} INFO - [2021-06-15 15:17:02,625] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:17:03,221] {logging_mixin.py:104} INFO - [2021-06-15 15:17:03,219] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 7, in <module>
    from custom_airflow_spark.dags.scripts.etl_from_s3_to_tableau.helpers.etl_from_s3_to_tableau import s3c
ModuleNotFoundError: No module named 'custom_airflow_spark'
[2021-06-15 15:17:03,222] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:17:03,254] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.635 seconds
[2021-06-15 15:17:33,348] {scheduler_job.py:182} INFO - Started process (PID=1887) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:17:33,349] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:17:33,350] {logging_mixin.py:104} INFO - [2021-06-15 15:17:33,350] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:17:36,196] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:17:36,226] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 2.883 seconds
[2021-06-15 15:18:06,542] {scheduler_job.py:182} INFO - Started process (PID=1916) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:18:06,544] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:18:06,545] {logging_mixin.py:104} INFO - [2021-06-15 15:18:06,545] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:18:09,456] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:18:09,489] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 2.951 seconds
[2021-06-15 15:18:39,957] {scheduler_job.py:182} INFO - Started process (PID=1946) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:18:39,958] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:18:39,959] {logging_mixin.py:104} INFO - [2021-06-15 15:18:39,959] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:18:42,881] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:18:42,914] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 2.962 seconds
[2021-06-15 15:19:13,027] {scheduler_job.py:182} INFO - Started process (PID=1978) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:19:13,028] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:19:13,029] {logging_mixin.py:104} INFO - [2021-06-15 15:19:13,029] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:19:15,756] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:19:15,794] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 2.771 seconds
[2021-06-15 15:19:45,923] {scheduler_job.py:182} INFO - Started process (PID=2007) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:19:45,925] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:19:45,925] {logging_mixin.py:104} INFO - [2021-06-15 15:19:45,925] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:19:48,794] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:19:48,859] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 2.941 seconds
[2021-06-15 15:20:19,350] {scheduler_job.py:182} INFO - Started process (PID=2034) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:20:19,353] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:20:19,354] {logging_mixin.py:104} INFO - [2021-06-15 15:20:19,354] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:20:22,388] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:20:22,453] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 3.107 seconds
[2021-06-15 15:20:52,562] {scheduler_job.py:182} INFO - Started process (PID=2056) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:20:52,564] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:20:52,565] {logging_mixin.py:104} INFO - [2021-06-15 15:20:52,565] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:20:56,759] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:20:57,111] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 4.555 seconds
[2021-06-15 15:21:27,786] {scheduler_job.py:182} INFO - Started process (PID=2086) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:21:27,788] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:21:27,788] {logging_mixin.py:104} INFO - [2021-06-15 15:21:27,788] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:21:30,992] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:21:31,070] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 3.291 seconds
[2021-06-15 15:22:01,180] {scheduler_job.py:182} INFO - Started process (PID=2117) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:22:01,184] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:22:01,185] {logging_mixin.py:104} INFO - [2021-06-15 15:22:01,185] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:22:03,138] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:22:03,220] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 2.045 seconds
[2021-06-15 15:22:45,880] {scheduler_job.py:182} INFO - Started process (PID=2128) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:22:45,911] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:22:45,917] {logging_mixin.py:104} INFO - [2021-06-15 15:22:45,917] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:22:51,099] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:22:51,384] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 5.514 seconds
[2021-06-15 15:23:22,149] {scheduler_job.py:182} INFO - Started process (PID=2138) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:23:22,152] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:23:22,153] {logging_mixin.py:104} INFO - [2021-06-15 15:23:22,153] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:23:23,039] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:23:23,053] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.913 seconds
[2021-06-15 15:23:53,264] {scheduler_job.py:182} INFO - Started process (PID=2167) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:23:53,265] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:23:53,267] {logging_mixin.py:104} INFO - [2021-06-15 15:23:53,266] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:23:53,723] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:23:53,737] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.478 seconds
[2021-06-15 15:24:23,874] {scheduler_job.py:182} INFO - Started process (PID=2196) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:24:23,875] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:24:23,876] {logging_mixin.py:104} INFO - [2021-06-15 15:24:23,876] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:24:24,243] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:24:24,256] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.386 seconds
[2021-06-15 15:24:54,402] {scheduler_job.py:182} INFO - Started process (PID=2225) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:24:54,403] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:24:54,405] {logging_mixin.py:104} INFO - [2021-06-15 15:24:54,404] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:24:54,813] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:24:54,829] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.440 seconds
[2021-06-15 15:25:24,951] {scheduler_job.py:182} INFO - Started process (PID=2245) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:25:24,952] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:25:24,953] {logging_mixin.py:104} INFO - [2021-06-15 15:25:24,953] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:25:25,442] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:25:25,457] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.511 seconds
[2021-06-15 15:25:55,587] {scheduler_job.py:182} INFO - Started process (PID=2274) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:25:55,588] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:25:55,589] {logging_mixin.py:104} INFO - [2021-06-15 15:25:55,589] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:25:55,967] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:25:55,981] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.399 seconds
[2021-06-15 15:26:26,112] {scheduler_job.py:182} INFO - Started process (PID=2303) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:26:26,116] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:26:26,116] {logging_mixin.py:104} INFO - [2021-06-15 15:26:26,116] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:26:29,905] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:26:29,919] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 3.812 seconds
[2021-06-15 15:27:00,044] {scheduler_job.py:182} INFO - Started process (PID=2332) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:27:00,046] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:27:00,047] {logging_mixin.py:104} INFO - [2021-06-15 15:27:00,047] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:27:00,721] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:27:00,748] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.708 seconds
[2021-06-15 15:27:30,934] {scheduler_job.py:182} INFO - Started process (PID=2361) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:27:30,936] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:27:30,937] {logging_mixin.py:104} INFO - [2021-06-15 15:27:30,937] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:27:31,789] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:27:31,815] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.885 seconds
[2021-06-15 15:28:01,914] {scheduler_job.py:182} INFO - Started process (PID=2390) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:28:01,916] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:28:01,917] {logging_mixin.py:104} INFO - [2021-06-15 15:28:01,917] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:28:02,643] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:28:02,679] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.770 seconds
[2021-06-15 15:28:32,814] {scheduler_job.py:182} INFO - Started process (PID=2419) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:28:32,818] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:28:32,819] {logging_mixin.py:104} INFO - [2021-06-15 15:28:32,819] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:28:33,727] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:28:33,761] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.952 seconds
[2021-06-15 15:29:03,966] {scheduler_job.py:182} INFO - Started process (PID=2439) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:29:03,968] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:29:03,969] {logging_mixin.py:104} INFO - [2021-06-15 15:29:03,969] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:29:04,701] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:29:04,752] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.791 seconds
[2021-06-15 15:29:34,883] {scheduler_job.py:182} INFO - Started process (PID=2468) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:29:34,885] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:29:34,886] {logging_mixin.py:104} INFO - [2021-06-15 15:29:34,885] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:29:35,490] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:29:35,515] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.636 seconds
[2021-06-15 15:30:05,643] {scheduler_job.py:182} INFO - Started process (PID=2497) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:30:05,644] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:30:05,645] {logging_mixin.py:104} INFO - [2021-06-15 15:30:05,645] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:30:06,379] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:30:06,405] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.766 seconds
[2021-06-15 15:30:36,531] {scheduler_job.py:182} INFO - Started process (PID=2526) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:30:36,533] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:30:36,534] {logging_mixin.py:104} INFO - [2021-06-15 15:30:36,534] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:30:37,170] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:30:37,203] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.676 seconds
[2021-06-15 15:31:07,336] {scheduler_job.py:182} INFO - Started process (PID=2556) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:31:07,338] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:31:07,339] {logging_mixin.py:104} INFO - [2021-06-15 15:31:07,339] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:31:08,104] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:31:08,134] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.803 seconds
[2021-06-15 15:31:38,280] {scheduler_job.py:182} INFO - Started process (PID=2585) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:31:38,282] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:31:38,282] {logging_mixin.py:104} INFO - [2021-06-15 15:31:38,282] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:31:38,902] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:31:38,917] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.640 seconds
[2021-06-15 15:32:09,046] {scheduler_job.py:182} INFO - Started process (PID=2605) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:32:09,048] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:32:09,049] {logging_mixin.py:104} INFO - [2021-06-15 15:32:09,049] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:32:09,661] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:32:09,701] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.659 seconds
[2021-06-15 15:32:39,881] {scheduler_job.py:182} INFO - Started process (PID=2635) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:32:39,883] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:32:39,884] {logging_mixin.py:104} INFO - [2021-06-15 15:32:39,883] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:32:40,515] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:32:40,529] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.652 seconds
[2021-06-15 15:33:10,658] {scheduler_job.py:182} INFO - Started process (PID=2664) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:33:10,660] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:33:10,661] {logging_mixin.py:104} INFO - [2021-06-15 15:33:10,660] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:33:11,219] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:33:11,250] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.597 seconds
[2021-06-15 15:33:41,388] {scheduler_job.py:182} INFO - Started process (PID=2693) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:33:41,391] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:33:41,392] {logging_mixin.py:104} INFO - [2021-06-15 15:33:41,392] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:33:41,968] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:33:42,004] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.620 seconds
[2021-06-15 15:34:12,144] {scheduler_job.py:182} INFO - Started process (PID=2723) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:34:12,145] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:34:12,146] {logging_mixin.py:104} INFO - [2021-06-15 15:34:12,146] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:34:12,805] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:34:12,831] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.692 seconds
[2021-06-15 15:34:42,961] {scheduler_job.py:182} INFO - Started process (PID=2752) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:34:42,962] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:34:42,963] {logging_mixin.py:104} INFO - [2021-06-15 15:34:42,963] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:34:43,626] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:34:43,659] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.704 seconds
[2021-06-15 15:35:13,792] {scheduler_job.py:182} INFO - Started process (PID=2772) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:35:13,797] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:35:13,798] {logging_mixin.py:104} INFO - [2021-06-15 15:35:13,797] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:35:14,517] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:35:14,560] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.771 seconds
[2021-06-15 15:35:44,689] {scheduler_job.py:182} INFO - Started process (PID=2801) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:35:44,691] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:35:44,692] {logging_mixin.py:104} INFO - [2021-06-15 15:35:44,692] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:35:45,304] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:35:45,342] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.658 seconds
[2021-06-15 15:36:15,482] {scheduler_job.py:182} INFO - Started process (PID=2830) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:36:15,484] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:36:15,485] {logging_mixin.py:104} INFO - [2021-06-15 15:36:15,485] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:36:16,170] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:36:16,211] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.732 seconds
[2021-06-15 15:36:46,350] {scheduler_job.py:182} INFO - Started process (PID=2859) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:36:46,351] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:36:46,352] {logging_mixin.py:104} INFO - [2021-06-15 15:36:46,352] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:36:47,046] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:36:47,075] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.729 seconds
[2021-06-15 15:37:17,273] {scheduler_job.py:182} INFO - Started process (PID=2888) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:37:17,275] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:37:17,276] {logging_mixin.py:104} INFO - [2021-06-15 15:37:17,276] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:37:18,055] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:37:18,077] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.809 seconds
[2021-06-15 15:37:48,169] {scheduler_job.py:182} INFO - Started process (PID=2915) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:37:48,171] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:37:48,172] {logging_mixin.py:104} INFO - [2021-06-15 15:37:48,171] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:37:55,998] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:37:56,116] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 7.950 seconds
[2021-06-15 15:38:26,253] {scheduler_job.py:182} INFO - Started process (PID=2937) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:38:26,255] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:38:26,256] {logging_mixin.py:104} INFO - [2021-06-15 15:38:26,256] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:38:26,884] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:38:26,901] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.652 seconds
[2021-06-15 15:38:57,033] {scheduler_job.py:182} INFO - Started process (PID=2966) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:38:57,035] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:38:57,036] {logging_mixin.py:104} INFO - [2021-06-15 15:38:57,035] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:38:57,399] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:38:57,408] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.379 seconds
[2021-06-15 15:39:27,530] {scheduler_job.py:182} INFO - Started process (PID=2995) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:39:27,531] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:39:27,532] {logging_mixin.py:104} INFO - [2021-06-15 15:39:27,532] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:39:28,197] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:39:28,211] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.686 seconds
[2021-06-15 15:39:58,343] {scheduler_job.py:182} INFO - Started process (PID=3025) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:39:58,345] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:39:58,346] {logging_mixin.py:104} INFO - [2021-06-15 15:39:58,346] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:39:58,777] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:39:58,791] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.453 seconds
[2021-06-15 15:40:28,916] {scheduler_job.py:182} INFO - Started process (PID=3045) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:40:28,918] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:40:28,919] {logging_mixin.py:104} INFO - [2021-06-15 15:40:28,919] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:40:29,423] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:40:29,446] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.534 seconds
[2021-06-15 15:40:59,612] {scheduler_job.py:182} INFO - Started process (PID=3075) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:40:59,625] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:40:59,626] {logging_mixin.py:104} INFO - [2021-06-15 15:40:59,626] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:40:59,997] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:41:00,009] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.402 seconds
[2021-06-15 15:41:30,134] {scheduler_job.py:182} INFO - Started process (PID=3104) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:41:30,146] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:41:30,148] {logging_mixin.py:104} INFO - [2021-06-15 15:41:30,147] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:41:30,659] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:41:30,675] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.546 seconds
[2021-06-15 15:42:00,808] {scheduler_job.py:182} INFO - Started process (PID=3133) to work on /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:42:00,810] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py for tasks to queue
[2021-06-15 15:42:00,811] {logging_mixin.py:104} INFO - [2021-06-15 15:42:00,811] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:42:00,812] {logging_mixin.py:104} INFO - [2021-06-15 15:42:00,812] {dagbag.py:284} INFO - File /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py assumed to contain no DAGs. Skipping.
[2021-06-15 15:42:00,813] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py
[2021-06-15 15:42:00,834] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py took 0.030 seconds
