[2021-06-15 15:31:09,427] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: etl_from_s3_to_tableau.download_from_s3 2021-06-14T00:00:00+00:00 [queued]>
[2021-06-15 15:31:09,448] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: etl_from_s3_to_tableau.download_from_s3 2021-06-14T00:00:00+00:00 [queued]>
[2021-06-15 15:31:09,448] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-06-15 15:31:09,448] {taskinstance.py:1043} INFO - Starting attempt 3 of 3
[2021-06-15 15:31:09,448] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-06-15 15:31:09,459] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): download_from_s3> on 2021-06-14T00:00:00+00:00
[2021-06-15 15:31:09,466] {standard_task_runner.py:52} INFO - Started process 3497 to run task
[2021-06-15 15:31:09,471] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'etl_from_s3_to_tableau', 'download_from_s3', '2021-06-14T00:00:00+00:00', '--job-id', '28', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/etl_from_s3_to_tableau.py', '--cfg-path', '/tmp/tmp4k7217ve', '--error-file', '/tmp/tmpkpmy_fbp']
[2021-06-15 15:31:09,472] {standard_task_runner.py:77} INFO - Job 28: Subtask download_from_s3
[2021-06-15 15:31:09,526] {logging_mixin.py:104} INFO - Running <TaskInstance: etl_from_s3_to_tableau.download_from_s3 2021-06-14T00:00:00+00:00 [running]> on host a1a5fa2e9591
[2021-06-15 15:31:09,586] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=samucg94@gmail.com
AIRFLOW_CTX_DAG_OWNER=SAMUEL
AIRFLOW_CTX_DAG_ID=etl_from_s3_to_tableau
AIRFLOW_CTX_TASK_ID=download_from_s3
AIRFLOW_CTX_EXECUTION_DATE=2021-06-14T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-14T00:00:00+00:00
[2021-06-15 15:31:33,004] {taskinstance.py:1455} ERROR - Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 23, in save_csv
    df = s3_to_df(bucket = bucket, sheet= sheet)
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/helpers/etl_from_s3_to_tableau.py", line 33, in s3_to_df
    io.BytesIO(obj["Body"].read()), sheet_name=sheet
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 299, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 336, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 1131, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_xlrd.py", line 24, in __init__
    import_optional_dependency("xlrd", extra=err_msg)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/_optional.py", line 109, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.
[2021-06-15 15:31:33,010] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=etl_from_s3_to_tableau, task_id=download_from_s3, execution_date=20210614T000000, start_date=20210615T153109, end_date=20210615T153133
[2021-06-15 15:31:33,043] {configuration.py:356} WARNING - section/key [smtp/smtp_user] not found in config
[2021-06-15 15:31:33,043] {email.py:184} INFO - Email alerting: attempt 1
[2021-06-15 15:31:33,044] {configuration.py:356} WARNING - section/key [smtp/smtp_user] not found in config
[2021-06-15 15:31:33,044] {email.py:184} INFO - Email alerting: attempt 1
[2021-06-15 15:31:33,044] {taskinstance.py:1509} ERROR - Failed to send email to: ['samucg94@gmail.com']
[2021-06-15 15:31:33,044] {taskinstance.py:1510} ERROR - [Errno 99] Cannot assign requested address
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/download_from_s3.py", line 23, in save_csv
    df = s3_to_df(bucket = bucket, sheet= sheet)
  File "/opt/airflow/dags/scripts/etl_from_s3_to_tableau/helpers/etl_from_s3_to_tableau.py", line 33, in s3_to_df
    io.BytesIO(obj["Body"].read()), sheet_name=sheet
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 299, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 336, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 1131, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_xlrd.py", line 24, in __init__
    import_optional_dependency("xlrd", extra=err_msg)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/_optional.py", line 109, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1852, in email_alert
    send_email(self.task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 62, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 97, in send_email_smtp
    send_mime_email(e_from=smtp_mail_from, e_to=recipients, mime_msg=msg, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 186, in send_mime_email
    conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 220, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1507, in handle_failure
    self.email_alert(error)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1854, in email_alert
    send_email(self.task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 62, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 97, in send_email_smtp
    send_mime_email(e_from=smtp_mail_from, e_to=recipients, mime_msg=msg, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 186, in send_mime_email
    conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 220, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2021-06-15 15:31:33,091] {local_task_job.py:146} INFO - Task exited with return code 1
